# Generated by Django 3.1.2 on 2020-11-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
